### ISSUE TITLE
set_colsz does not

### ISSUE THREAD

**Issue by raphaelcohn** [lunarmodules/lua_cliargs#55]
The function `set_colsz` is in effective, because it creates a new reference and assigns it to `colsz` after `colsz` has been passed to `create_printer`. Instead, assign the new column sizes to the fields of `colsz`. Alternatively, we could consider making `colsz` a public field along with `options` allowing easy expansion for downstream users.

**Comment by alerque** [comment]
Per discussion in #56 I'm going to close this as it the failing case cannot be replicated. I'll be happy to reevaluate and reopen both the bug and reconsider the proposed fix if a failing test case can be demonstrated that we can add to our test suite. Thanks for taking the time to report.
