### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Tieske** [lunarmodules/lua_cliargs#60]
Just noticed the version went bad.

The new release `3.0-2` did include code changes, but only the rockspec version was updated (pervious version was `3.0-1`).

Rockspec versions are to be increased only when the rockspec changes, but no code changes have been made.
In this case there were backward compatible changes (refactor) without new features, so it should have been version `3.0.1-1` (under the assumption we're on SemVer right?)

**Comment by amireh** [comment]
You know, I've noticed that but then thought that we were specifying the patch version after the `-` so what I really meant was `3.0.2`. Thanks for reporting.

Is it mandatory to specify the build fragment? Can we do `3.0.2` instead of `3.0.2-0` for example?

**Comment by Tieske** [comment]
Well they are components, so `3.0.2` is the `lua_cliargs` version, the `1` is the LuaRocks rockspec version, so yes, it is mandatory to specify/append the `-1` as in `3.0.2-1`.

iirc the LuaRocks rockspec versioning starts at 1. It increments by 1, and it resets whenever the application/module version is changed.
