### ISSUE TITLE
Status of project maintenence, suggestion of transfering to lunarmodules

### ISSUE THREAD

**Issue by alerque** [lunarmodules/lua_cliargs#73]
It's been a while since `cliargs` got any tender loving care. This message is not to blame the maintainer. As a frequent FOSS contributor with many projects on my plate I know exactly how things go. Even if `argparse` has some more of the momentum for Lua CLI argument parsing, I am personally a fan of how this library works and have gotten a lot of millage out of it. I would rather not have to migrate most of my existing projects.

That being said the issues are starting to pile up. I see almost 1/3 of the open issues here are things I've raised over the years and have frequently had to monkey-patch my way around. I'd like to offer to help maintain the project so those fixes get upstreamed and I can keep using it as is.

I offer this as the maintainer of Luacheck, LDoc, a contributor to Busted, Penlight, and others. This isn't my first Lua rodeo. I've also picked up the maintainer reigns on a host of Vim plugins at @preservim and other projects as well. You are welcome to review the history of those projects and how smoothly the handovers have gone.

I would like to propose this project join the umbrella of @lunarmodules. You can still be listed as a project owner, but the team there would also have admin rights, and I could help shepherd the process of getting PRs handled, issues triaged, CI brought up to speed, and eventually a new release series going. If that sounds agreeable by all means have a look round at how we've handled other projects in similar boats. I'll check with the rest of the team and if nobody objects we'll get you an invite so you can transfer the repo to that namespace. That way all the old links will have redirects and no existing use connections are broken.

I see @Tieske your are previous contributor to this project as well, does this scan by you?

**Comment by Tieske** [comment]
iirc @amireh created this in a distant past but is not actively using it. Moving it to LunarModules makes sense to me, so we can set up a broader team.

**Comment by alerque** [comment]
Gently ping @amireh. This just came up again because somebody submitted a patch to Busted hacking around a CLIARGS related bug. I'd like to see these fixed at the root!

We can send you an invite to the @lunarmodules org so you can transfer the repository there, but the invites only last 7 days before expiring. Please ping back here and we'll get the ball rolling if that's okay with you!

**Comment by amireh** [comment]
Hi, excuse me for not responding in time, I've been out of here for a while. I'm totally okay with the move if you'd like to make that invitation. Thanks.

**Comment by amireh** [comment]
Okay, I just got to read through the posts. First, accept my apology for not responding to the other issues you submitted. This has pushed me over to finally clean up my mail inbox and especially GitHub notifications, as I was getting too many for things I was not responsible for and in the process missed the ones I shouldn't have (now realizing, even ones dating back to 2020 :disappointed:.)

I wish I had the time to properly maintain this, more so when I had to deal with other CLI arg libraries in other languages over the last few years and found myself missing some of the design decisions taken in this one. I'm happy you offer to do this so thank you both.

The security issue made me curious but I could not point it out in Busted's PRs/commits -- would you give me a link to it? I'd like to learn of the mistake.

**Comment by alerque** [comment]
The LuaRocks.org ownership change is not something you can do on your end very easily, but we can page @hishamhm about it and I believe he can take care of it pretty easily. With your message above authorizing the change there shouldn't even be anything else you need to do.

And thanks again for dropping by and taking care of this so your useful contribution in the past can live on a bit longer!

**Comment by amireh** [comment]
Great! I'm glad it proved to be useful, and thanks again for your offer and your patience.

An aside: I've been working hard to make [this software](https://syng.dev) work as a business to fund me in place of employment. My plan is to apply to Lua if it's received as well as I hope it to be for JavaScript. If/when that day comes, I'll officially have an excuse to work on maintaining a Lua library! ;)

I'd love to hear any feedback or impressions you have on SYNG, even though it's not usable for Lua yet. The concept is universal, although perhaps more applicable to non-typed languages, and there's so much room to improve with the AI advancements we're seeing. Right now it's a "structural" search, but the goal is to arrive at a "semantic" one - sort of a dream of mine.

**Comment by amireh** [comment]
Closing since there's nothing for me to do for the LuaRocks transfer. Feel free to ping me otherwise, I'll be paying more attention.

**Comment by Tieske** [comment]
thx @amireh !

**Comment by hishamhm** [comment]
lua_cliargs is now moved to the lunarmodules user in LuaRocks.

BTW, not directly related to this package, but I recently raised the question that [I think we need to start creating project-specific users in LuaRocks](https://github.com/orgs/lunarmodules/discussions/8), so that the API keys are siloed to the particular teams in the lunarmodules org.
